# Generated by Django 5.2.4 on 2025-07-22 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_rename_financialgoal_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='goal_type',
        ),
    ]
